apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:DS1kUL5ITbO68Ny7+C2A5jrSwpcE6Xe5fOktTDp30U62fz50rleXSBoJiw9F6MJfvkYOHilma3HwpxAAtatQ3IMEHWBOHtLg3AvefLrmO9GuSrtuAI4NYVh8LPGzihmSAJRoHNAk6R/EQoY0K3qWv1iXjj72hbcM4H8g5luixhLpcnChv2dFAuz5miw4n0ndzemlpYt0sUaVL2ebcrhedEjEdDWhx9S0iDqnSmhGx6d+PFZMa9Wu3P50jveleq/nAeIrmBf8P/2UuFUg/UWAZN7gVdqsHdWiR4XwVJcTADvyNyILv9oQX14OTFcDMhv9FhHOD5/PP163xObv9xrmaLfq2FYcaLAjswff5B/sISsFj2fh6k3zp2oPREOxE4HR,iv:0gGF7mejGhs+O1rFupuhsm5wzQ65HQ2Ekm+g0/uD/fg=,tag:t7pCSEC5P3hj3minqQfmfQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:NMc/zwPa1HjVMxK0/ZUfpC7rgDzOhlYTPelWNAmJQMJ6G8HYGcW/y1QCaIZrm2M0IYrOXUKXk036sDLBj9xJlU2jXrCCRRQnMOWpxkgtEZ5X8+zRavBWZXa8YSvOEDI5687C+s6VPCGuVUtzzE2Uv/RFNLjNwA5usOmx5kKz+egBIqSkXHGEhu2P40nP7l9fk5X9vQdGEc3g9NQEtzhvFgcL/dMldp7Lt5FrrtBzOMxuyKkY+/++KbdrBDX+Kndfa/vbGeC8qCdB0Py4+g==,iv:OS19xY+CCkQOO5izAcOrVlvQSJjv3+RGbO+zX8YINuM=,tag:nNAc+1LPsV0yONKZIuJGag==,type:str]
    known_hosts: ENC[AES256_GCM,data:RVvI3PRikmS1LVgL1BMLMBlJfO2P15MkMkp4+ExLYX0Ml6SuKg5BP4C3P8maBEQEw9AKpkL6IG8CrVdBBemzwL/pBSWUMDR7gX6uu25Kw4fxI6tWkt8i5DAATedctjn7YBPv0nIhR9VykqIYIOn55NNaEW3bhyBwkOhuuStWpYc0ZabEiY+gtorGVDrLyQCpAqmBxBFwEh3YGS6+GrnARddsc4Hv0HeDYYSH,iv:sb5pnlpKMAEm7O5VkqcLRu+V7K4ZK05R9ofuevwcEwA=,tag:szEah7mlFybRwDp8I6T/gA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1fs9hd9ex63f4yc9l80knzfsa42gnhjcerz2ldyz7v780pefunv4qf8v8ew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZmdFZThmZ1lZSWRROEFx
            TVRWWVBqU1BubERER2o3U1pEbHJnOGNwZUJRCnhvTXJObXlWSlFSazBabUdYRjJp
            bUpHa0l4VHNLaUNXQmw1MUxhdnNMZkEKLS0tIEo1aTg5VXM5bjRDelpKRCtVZlRi
            SjR3RlM3alBVOTNSRXBkejJ3QVYzQk0KDVagEbs0TIodmuYviCEMpxwqdWMygV9i
            Y07XRJGprPqeYIVefb3ip4TQEa5dnxb9XVe7xRPqr64ykmEaoItJCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T15:55:25Z"
    mac: ENC[AES256_GCM,data:5MTSGpFBS3uliafw3SwEr17dZ1xKGkVKUPLgkg5d1AkJdFuR8qWGuWd3gjKjDBQnSH9Z95niyBVIDyfxo/pOHhBVfIqsfdcUtLs6vggGtd3TG1ExNujj66iI6acohp7MVDF5Kg5fUlkQyevx3WUVKXku2I39rmR9IiMKQSTe2WY=,iv:TOm+bQF8rkmSk+K4CAPS3zXSLHcb7A97myWZPJ05rQw=,tag:jlPfQQKXQkuIIpquemMMcg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
