apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:xWdmSA14wFMDSF3UGVGahheRwq2ZcC9rd0baJWtHJxATibycn6NVY/3loq8YEx20pD2bjVPHg5czsI49aHTR0uvSz8Ok7TaAzJ0b7uP5aM0AXZ4IJJJjzPtZnLiLfNQ+2AJt+pQ7Cw2tmh11xFYQkGJH4Fmyjm5b5gAquZxGcvArF23yY3V4sJ+GkB4LRn3hxJ1gMCqX/L2iqDghqA3O2PbDoAZgEYPJwc3tnHC48lqB+sXVVKxUNQHA+dc40MmzcZSMPAAjKGkx3upIkuYVqmEhZ9x5zF6lc5sZHjxB65cSpcp/yyM+Tz1xyuvqO+M5dCDwgsrvKyDPwwKGiJ3Te9mswdApQkGjxF0xnKdACbYDVMAzXGOiNrZkBNIyOAA9,iv:cdHIhIebq/6moADen4tk1sEcg+2dZ/9VrE0L9jOOTBE=,tag:CiK9Z0FTnbqnOkpxjKibwQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:xhITGfb3okAKzrMMxdVySslulu7Kf5MqofKIyzwIDmpkfvy8vBqsUzsxihuYDr8fAllzpBf9XolEJ91Qj2ge1tAnI2Ei/RlX1Mw519XmRB9GG6UnbVN+BNbrphc8E2FioNNz+ju2LNmbYgP4Qz11j/OJh539S7UFiH6mm8fafm8NtqVfphKPKnSxXYl3DZ4X9U+kERhSFyRcjifeDPOi7exCmh2tZYLO8xf2yhQBfsekUJa/p771rQAZbt9zWYoiSwsHVWwnd6mJRX/EYg==,iv:JQskEBhN+imA/6Upp0zpQuddYLbuL4X7SSZZYVCSuEQ=,tag:FjZORCAZmGnUZJ2kkMurtA==,type:str]
    known_hosts: ENC[AES256_GCM,data:ihHFRpRDfBVX91tPufiDc1J9ogAeLUVHJpzOlUL/L6KE0kDmqWf0NPrHXCqSCv9Da6QrYy2alK5aArAVNiwi+fPkDmJe3sMF734n1etagS+ruD/hPIgLS3aCEu3QS8uhZcRB0WAP1/b7/enN/5i59z68YVWs47/DzYpzuoqTXOBtrd6XCQNq3xVcq/uYcPw2mQXzL3MPXLhJUE6M6TgDmyeGweAuy/rvMkga,iv:Tw9MyfruAlZe75p4NM8oum8EIjhtSe5+qXK0vX26FZM=,tag:V0fm6skfzXml8VUHygDKbg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1fs9hd9ex63f4yc9l80knzfsa42gnhjcerz2ldyz7v780pefunv4qf8v8ew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNndFaFBaNUJ3NE1URVAv
            b3pacWUrK3pPeTBqaElDNU9mc1ZuZjU5eG5ZCmE3ZzZ5amhHRzg4L0FwRGNnNGEw
            Z3hNYTErY0ZpZXc2cTJ6bEI3RUZRQVUKLS0tIFBYVFlpS3EyUXJVODZ1V2FJZ1dj
            U3pINWVMUHpwRi93clVCUEJWNXN6djQKkiPulsYR6uYLqhd8MkdSsvvnx2XH+HII
            n3yDf/gjHahPbrKO1TY5JYyKRrzcqZrO/iWP7XqebDyiAO+f/Xkm2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T14:27:58Z"
    mac: ENC[AES256_GCM,data:V3W4xsHsXD0d65OEQQUS1em39ZhhFBOCIV8m5E0PAiZIcX/z9T0omFl7wi3Tj/wTNvyQ67nOcV6cV2hVv3Zdajx7Menkh5cufGj5gkkbmhtL+Md2HwnDGs5M39Q0/ZdCipnuWq1l6InHACZViE74BZ7tygxKlvgZJMGTF9wfHfw=,iv:Dpjvd4e7n9X8h7Ofbefc3Hxk/iE8P2359q9wK8OYxOo=,tag:Q6s0UHPKsqylr2LmoVGx1w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
