apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:BwAAWU07MfcFzz9AK/69gH/N5kKlCi+h3CJMw7fp7z3ley2XVs0YSPLGb3hUXRfJS6JxbSheCfHzbmcX/fEAy3n1OjUrkgh6slzJuVQvn+6kPGc9dxCSfTzjtuUEguGJ5Vf/o1NMGmjLW0EOeO88JRM/j1kJ1Xx2gvIOQHyO1CsCRILXkOvivGN2Zou4EhBKUe44i4a1818KZJ6rvZwamv0wiBOvWPwucQVbja1E4ZPHInkwTRYmlc7mTainWLyRo7m1R25dqAcLBg1yEpYCALVo3aRdS0PzcayLRuPMzaADjfUgIv5VKO4y2K/slQKHv27Bv06WZApkWUi/vCv/omuJQu8bjsxXFtQ3Cyjp79ex5K4fwoKYuGpCvGeUINq2,iv:C7lv1KEBSVr1LOYPr5TQyv8eGrd8x1jucHQ1HUT/0Ss=,tag:pMCHvxSzO9rTz/93J9R1bg==,type:str]
    identity.pub: ENC[AES256_GCM,data:rz3+befRNxbkRNLffo0nEIYD48c304TdIAyJgGeb5WGqwu/fevWLIkmVpBLtjqFG7zmyCIdDvjjbAWaQbOPElT/HAGH3Wi4JuCBaTccApmhkDfhE0eF9I6wtfR+xuJsSjUa5Qi+DFLnIzCCIGPTcjNz+koOX8hQ10tAto+9a0h+5+w/WABWIuz4+JI1B9ecOlAtNHQ6YAX3WIIYLwOOr74kLAbE4F6rYVg9D3ZTSLI7mrGg3FGTswCz20o5oFX/RiXPHtuwnZXnkI8cKZQ==,iv:rQzFBgj4NzVsZ0+Ms1XcwxycqIH0ybwiOP7Y4/8MV10=,tag:tUCG3+9TFo80Y81/ZGrskA==,type:str]
    known_hosts: ENC[AES256_GCM,data:eDjtfhFqd+pNyLQqBvp6/gmdhY5KrjCC57J1Ohctm2ujH5quJx2CCOICnX2Eqxss0selHDIXOX6HUONeYBm5BWgUtvaiS3dBC4vYAP3FqYruION80QOQ9sZkBjb3ekzRIZE1V1iaHLtcv7RTnV+02XCppfBYfjcQG2xQKlZlgG54EbdrYaFhjp9exBsJRTwlFHY6BAxQJe+Qz35Y2PJDv1f4nfq7npYN7rpJ,iv:CISybsPN900iCZB/2twbyv/Uc+YbbJ5Mae2fVeE2cWg=,tag:TSUL9pV2iDsmuVYIdKgCFQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1fs9hd9ex63f4yc9l80knzfsa42gnhjcerz2ldyz7v780pefunv4qf8v8ew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRS9ySkhhaUE4eEdvR21Y
            d1NjeWF6Qk9YdGZBR2pKQ0J3cjMxd1o4SVdjClVHU3VubHh2MFNsejJhS1pRNnA3
            eURUcENqWlZNMi9OWTVkWnF4aWtKalEKLS0tIE5YY2NxdFdadGVwK0tsK2RuUXJ3
            SFBjQkoxMVpQbUZkRi9Ua2J3bCtXUGcK2kB8yvk0nDakBh5hTp1P0dz20oY1Iahr
            3PtkycD2y/03ONI/peggCA1srfUR4Pf9RmFrJmolT/350ivoYdPxug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T20:59:19Z"
    mac: ENC[AES256_GCM,data:HGGPbPNCOcR8E7JVTXfHvrJXWd+Jg2ZgQ5nHR78gLBI+G1pK82vba5SY5FyQXa6lQhgONMGFGMyg8FpjVOysXf/u043iHRmoFeQook/ZqEtDFBInavuaw55SJUwz1q1RVroaEXwK4AGrma192XyqW6W3bIu+36W0zew8p9ar1aI=,iv:lXdH6Q9X4WAgTMidQI80AGIJuWV+eeqJmUv3uVGCzPE=,tag:AowkNbMxgWNOESfSr8Qm8g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
