apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:15IATiChl4rN7U57brD2BPvsd3+KX9PJiFP6I5zgtjJT/g8+KlmLQ84IU8xyPMTAjdJsBrXASzwk4C0YW/QrV3pFYv9F5NuXtrCKzsNH+wgLYHGyergEDLTDV0vxGUfQuiaLYpIWTMGm70dqrBsloZ0Zwfjsza5zMdplo6Rn2AvezEYFu4r7hQ8p3CCVIQ3Kb3H+CBF+NZirlvwYo80tJDCTMUWQi0CZrWrsc8R/obe9ZkQ6twMGWznZIqzq1O9FcaajJMOa8pJ1/CE/kQy3vYxE4sKhvy2U+on5umSy9GnKv2bt1Qk4+Wlp/ifMzFOriLc2977/Rm8iACXge+ZdjYDywRrdTog/okvZx8T99Jmitguedd5spKSorNBinmma,iv:jNk1ZCCEYpwsNhk7OwLbXEbdGZivRg/2NdbcT3S5qlM=,tag:ZHvZC99vGHQO8jdzj5H+yw==,type:str]
    identity.pub: ENC[AES256_GCM,data:RZxNNQzDaj2dSmrR7CGoOdU6HRafq2wcsK5RwkLNhbAJtPEuJ+/DXuehkEqFjWp62GR1G83g0yKVfu4n9fFoP6A/yKPdQy55lCGa5zQwwjm99fJIEA89RIQYdulrh70ZVkg90pooPqrT+18w26q3Ggyt6CzCfMb+E0ZcaIx0uen76EY+86wWV4+z+FASBPHgkDSfx7xZJf5/MuwikKFJCunsWgQjWSdJGkZcPcyJqUjPpo/wtj2y3Woimg/v2YuCdUVZzayywtzyq9HE2Q==,iv:Rj1tq4zULQd8To4zv0KzNlli+vv2Yw/ZHB56f9hpc/E=,tag:otEjR9ohOdX7T5gA0cVBKw==,type:str]
    known_hosts: ENC[AES256_GCM,data:zmHrcHTjpPrdHjU3V8CgouRshTgpyA2SdMdV51v4aYPIm65hL1Dl91uaBor1BiBuG7sf7BZr7nq4VsL051PWT85xWxQfyfEhBH/ujkr6I0zxVNoaz+hn244k2vnJxC7jz5JxHQRTI8qW25+77RjIOEtSBAg1dxFULxZSfHYpAWPjhV/kZ/yq9w8zTsEceDasG8D70vSzSvnSiGPXO50CxNqdEwCOk4/DU/mr,iv:MCTZo3Y5l6nbg/hjXpVZLEo6CLFrDZHOSM10QddPwjc=,tag:jaGx38hSdIITInRWH33YGQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1fs9hd9ex63f4yc9l80knzfsa42gnhjcerz2ldyz7v780pefunv4qf8v8ew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dXBZVmMvNTc1UTIzaHVM
            UkcyaitTaE9kWFhqYVhWdGVyWkpyVTl5MWo4ClJ6TVBjMmdhRTJFTDYybmk2YlNU
            azJUbjBkL2RPbm5Lb09Ia0U1ZXN3T2MKLS0tIGhSZzVTdnVXbnRzNXJmREpxU3pv
            V0JVdlZnRUdNbWJkYkZLb05zcnZlaVkKCfDSX3TJCjS3ESs1tCmgOkQ9re4I8Zjs
            OrBkH8NqaR3thFTFgyFRg6zhE3MOE9E92f+i9ZfQkUOWLalN37PNsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T18:22:31Z"
    mac: ENC[AES256_GCM,data:ad7zZ2No28+RpJwO5s7D2P3Y4ZDgPv8TpNxWwFIOO6LzOMedOEvTprpu/EGd36OUUQCOEwmqiJdTMv33qR/hYdld4EePv/bgJqYyuIMfBUtGHVU0XdROZQTg7i8oAlpTV3U+EbR5l+p/P837TLOsAD977JGESzmZP2kRxswI68I=,iv:2Me2g9DOdTgAuMl/vrnzE/MY9EH+vmaDr/p/KO09Owk=,tag:FRYLIaaALoxKT7i8UIGhpA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
