apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:pfNnu7mS4jXifjhJ/8ZG2E/NxGTt19qOAQ6rZKn83Ph6fYOKScmZJJx59FBewlEaYKZcw8tghEfJrPxsmvd3A5MqnSeTzSXbfwPXm2iA/iXgzbLDv7ytTTx+92g/AOfnyo2thZXD0Op+UuqQkyOQwvbAmsY7pnWVVPXEl/Lf92B91PrqULW+VIkqUC+UUGHTZV0XttenMfzOarQULvng8CC1Qh1+cQowyk5w346aVu3QBRhp29DbTNzGTAXWRHUrj3h6RwjSvBW5y4Sdef6bfyRECcJErBf7tL+h0gz/chdRz2LYbjmLYXLCccg44Qs+lbuCFHM9SO3WxJHehxnhiD+9saT4w65xZFf25XMJ6bJ8LbxsZsahFINaquMP94oD,iv:gsqn4zuaa4J0nTON3sToPi1CS6Ejwp6usNqFXAbl+Hk=,tag:RRKKS4uoCkrJM90kQ3WNLg==,type:str]
    identity.pub: ENC[AES256_GCM,data:bgXcyGJ/i9hpAVljeMyi36WzjDTnvmbNPqzhoJhCs2XyJvAJgpRBsNJErJoNv4uYEL1dLGMnuAak/xByYFxbo7Gs0WGUcw7zNzSJXcBighRvB/2Li+Od0az0e2CGY0nZA4MByfCUCwjPfXtIG7EdLjY2ZL1HQoUng0Kgb6HeKZfvtdmd6oAQubclppL4ZgxODa3i40RnjZEjAn7S8Hp8Y0LYg3OfPVwUHqyqbWwAiJsQTxW8Axml7kIPXvFEDme/uSiWeB+4AhOpBF+fPg==,iv:WMMe6FMe6O3ItSSTm2p4YiRy1GnJYMbVRYtH8NxKq4E=,tag:mEPj3JNOFlXHFZhXl7DHPg==,type:str]
    known_hosts: ENC[AES256_GCM,data:YZrxSdWleOT6JFsiHtcNVoUMEwUjqb5bLpHUh7IV2hB31Q7P7LMADPFtx6Nffs/a08Y5g9T2OqymxVUZOiBjcs0Jp1rax260NJe/Y/K5eXabQhrSqNFY4KcgKft5mbh4e5/UiuiO2zCd8k/Wawau1gKL/fZFBkIPq6SwgdoCod/K1y8rhmlTPiqP2PLtB0MDecYLatWthRBgyQpF0rCC8aa0aybIMRqf/XRt,iv:5EvZF3MlV+5GfvqMrNs4hEijtNMeEsT+lbYcjMowCKk=,tag:OgzjbjNeSBZ0KiOSL6nalQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1fs9hd9ex63f4yc9l80knzfsa42gnhjcerz2ldyz7v780pefunv4qf8v8ew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNnBJQUpIZExqZ1IzUEg1
            OVQvcWV1UmJEMEl2dDU1ZWIwdGFPa2dXV2tBCmhxSW15OUQrcUZVNDVKRU40anl2
            L2R3dnA2NUFZaDNuSnZaNXY4QUErTVEKLS0tIGxCZ2g1ZkdyRlQrbFJBNTVaRDl1
            WG40ZHBteUF1dlB0RkNVV1VnaG1GWTgKp/M9XHIkYqtl3xzI7oECtHqtjaa901Id
            xo6546ZWazYjagThLCvYKbhdjyQLVQMSiHxRBtmCEUJiTmhdkmuHgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T21:55:04Z"
    mac: ENC[AES256_GCM,data:K0OtWpZylRh7IKVtLTCEruZ5WSNNo5cwizvR2mRsMTr97nd6/LddNJ891ld8wU6rGiO+Vq8sv+whDlEiaSYPL3PVLKIVgOod+7s+i2nmeyL4OONq++CjhCLXRaghb572dVMDLPgkg+eWdZVAOtV62XYGux5yR4Z3IW9wruqPopQ=,iv:zEK8VgZRW+KBv3k+rI8GFtja4IP2as9V/kqplZPd/KQ=,tag:d/FFpMdOVxJj+iLBbBc4Yg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
