apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:rdBG0WL6MOJxE7PiZnKbbAYmhPoYwuJElfPq6F8i8do+fQhkcYNaeAshP9XqTA7lxBUH9BvAuBqLIibimgRQDY1pJAv7rTEStj+g1uO1/p30jzUMWktwKuKPggPrtiEORrEMGX0f5Zr6fLGpNnNDT2KEq/tmPKZ4Or3vL7wzRanSPmvB/r5yMa9V+H7P3ZqEzRBwIQCQZ49TcAkNqxynmATequHHxOYsKw4Moy4Ra55D8Lrvp/p9HAGN8bN3WLDaaQzG8TKII7mn3e1pwQmkaociKrakLGlVQZvzGOkXQwTsRFiFtz0RVpTT2n7MnqMVN/EVtip54DFDnAjm2xJauFBuNjAlT2bgNZG433R3BKN/mB6aFb41/Xr587lhLBOn,iv:Xq0E+WWZs5NYPSzFbU6uk4ap2Lg58IaP5Aj5HgfCRKY=,tag:1hR3qYsRmn1sCPJUuJBcmQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:4cGk/ukgdlArUrj6TSE8gDY4zz26n0C3AeZf31Gw9jtyf9f3BiA1OlvhasGHXX25y3HGc4rt4xbtppiIFjxBh+CJLcSrn219K2Vnkt7Gf9oLETEbVd+LZb7raZARdXIxgFHmHP9r5IB6can22+OuJJLD0L8xrsGDL7ANtxFbXGr/Ap15iGQXImMs/cbZc/TVU/0EH+V4n/CVL5WN0gYfXiToaSzz3m0l+XovPx1JGDp6IPRuzeR7cOieWVzcNpeNY3VL7Dt8Axa3E+Q/tA==,iv:BpxiKybvSdBxWoqjqQQxnsLVAcW+JUx3K20TLVn6njs=,tag:TTTJPymmG4V9AUnUcC6Izg==,type:str]
    known_hosts: ENC[AES256_GCM,data:aUgsOWRF5SRg1PVV9YwHrQqMKdFbqNHQPOBEMFqgD4HpEbRgmZfazgvO8z+bp6J+XnsBBR4Ln+RmkKDnOSHDmMI39eSg2D521FqCdHkfdR93fNZrdkYrz9N5/QQ7bw6kQhHtvCSxpLG/GFnm5qGL9gso55R23fcRaRvBGtqU3EPGxH2HgLcct/WzKBTjaseC8zs02AAodtG9LpziBLkYCCKh2XIfoV+de5Ss,iv:gRZhSkDjRDSUuMRbJQZ/FiMpwVSm3+UEowDvkIjsMP4=,tag:We6ecGEZWXAFFQ2ZJi169Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1fs9hd9ex63f4yc9l80knzfsa42gnhjcerz2ldyz7v780pefunv4qf8v8ew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGb1pnbEFXWS8wSGNubHFn
            ZlZGRmVTdVl4d3NweXh5ZTZFRlZrT1pTNlY0CmNVSngrOG9DamZSWlFqYVJqK0t0
            Z0d6OG5KRGpCV1dBeU1qdWQzVXovWFkKLS0tIEp6UUVidFoza1hqTVI5UkJGelFK
            V1k0TTB1TXBQZWxjdEJHN1R0cGJYL0kKR5VSUWkSNoRj1bpVh0Z3umCK/OXc+3MT
            zlZiuHVaAue9BgUwFTV8c4y/F2N0VqD1yjYxWsIHORqx0TlhowweCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T18:53:49Z"
    mac: ENC[AES256_GCM,data:6F+2KEtxeh4FwQWbREbv7zJyTUrBl9dCgLqRh8yWHQNDxUtQv9nFHrDhOHa2ksumjSTMh075IX/5wP5r2foLPxjB3vKtbFon1ecEJIZf5pMS+4VcobgP1j2gCRf/0pkHqd4SxfQZ603h+Jwrn5CPUi/LrIFysZ+mjS08PBam+Pc=,iv:GSyP+zhqCFs+SdSzhWV56Uc2In/GSaTzEJVYfAQ3uoo=,tag:9jtlQElMx+Uz3WXZ0uUqtg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
