apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:XFQylzxvrk45X9F5TsNUA75sz4FUoleVf0Iw46R0UgjgdZRKDXqcmZrzO38xKaIjxHixmvaD0xED+UnnPR1a82ajT+ALypduky6jeP0hxZM/AVXshmPKIxh1s/sTYo01E9VTGvs6zwEVNvUx7VvxmncJVuHobbWaLne53+a/zK2kd9wiGzIRKAF9+g1fwZ1XjFMrW8ac5KMDZJU7KkGgHQFky8KTmkB8YfFvPT9gyvKCZSAaoDjsOcGU1d+TutJV5UOMUxPdLPlmUIX10vF2WFHu+RCfahTAnGVT4f1f2sIGVXpD58zsHTAdWA8Oq78zh2nh2V35lDPyVI77mExyzKz4qgHR/Jvzp8/diCceaIFeFaYuMj7ewHV7L8ZY3Z/B,iv:MFDXUKV9WUbVuN0834sgho6L3gbd/1hZS5beekkesko=,tag:auI71+aaXfEG6NqpA/qHww==,type:str]
    identity.pub: ENC[AES256_GCM,data:Ap76cPF6XlKZeRDeufsiE9HdfM+yJ2Nux39McuPSyR4HB0R6aRZLKryz9vxQ1X4yzqB9IjhslMzyiLEec0t7y3fdLnZdLDEWm0IHj+u9SxtzMDpK7dw0qDvwedhJEhMYi1+afJA/WdmO9pp9i5/ottSd6mW6+9gO+vw6fYcl37IL1e7Z3BSCalsZeYXatgF2PsitJs8WL/2gZAAP/W7rq5IsNXYgaQHfruQGhn08VnHF8FvrOwu8wXHcFLXRVkB7UiLjYZEHNVFHyTs1xg==,iv:JxWsAug74ibDl7HZ8Y+ShhPoWa2vy7JturYkElXZfoA=,tag:fv7oqvrx3eXjG4xUPBA+dw==,type:str]
    known_hosts: ENC[AES256_GCM,data:TQpQJAYi9f9eYKsjyPLq0dvMMuwl7rucBFIIsIa34PlPJRhER0PK9sfMRuKtOauxFofgt7qZwuoEYefHjpXO1PbG22QivZ0Hie2Q7dn0vXhFlQ1PXPxoHWeBKQt2F8zD3k9w3zkDtyHKOyGAhOOanpXIqm/UaVpV7Bzl1PSy4jSzfq/Rbbqmf1C0dYS2nDLmc1igFncBqbW8uikRzOG3tS5/1JRGumaA3yhp,iv:DcE45xFYO0jDbeAVdK0X2SLyzKUgKSo0tyvpaYevH9w=,tag:4cZ1byDV2x4HcRdmqrkZAQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1fs9hd9ex63f4yc9l80knzfsa42gnhjcerz2ldyz7v780pefunv4qf8v8ew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbUZmeUkvczM5R2d1bzhF
            UC96YmpNK2Y0WHpDVXdQU2U1bzVhTVdUZWlrCmpHT0FreW9oelBENU5taFlCRmFk
            RnFtSnVSbHUrc0FmSkRJbmlIK1Fhc2sKLS0tIEJMVWFhZkFQSHEvamMrcmVNb0tm
            czR1c2xSYmlmcmQ3TS9WNXpJbm9ZcFEKnNO8OKDuaylc3jtndARSp+8mvZJJz8PW
            EtroAhUdvIDr/lMsU97DxuRXv8C4AKUGwjnzulVtoK/9MAKShxvC5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T16:43:14Z"
    mac: ENC[AES256_GCM,data:pRehjuNy3OJuVlHElV5lXxHYg/RVdvuUBLElz6CYCpZAzygXTI84wLy8un4sZqMUqu86Swls2Nb98DY5F/X/m9HRFUuijlGzzpXTPG2/YnjNxgGgkPBKyYg6ehT8ZnDSNwaVWix5TM6z+Ibllfqdaq9TIMQ3I9EWiChBy/Jv5hc=,iv:TyF4p87eMez/UAmbFuC4vo3o84z1OFBPf1dJS9LU9hg=,tag:nKtLQMw8VCxVbdZKDOqecQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
