# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: huginn
  namespace: huginn
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 15.29.70
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: huginn
  values:
    TZ: Asia/Yekaterinburg
    image:
      repository: ghcr.io/huginn/huginn-single-process
      pullPolicy: IfNotPresent
      tag: latest@sha256:2c4461b332fcc7e041d7c0f5d504509fd725121ea35de679d6b9a6657ff9057e
    credentials:
      backup-cnpg:
        accessKey: ${VOLSYNC_ACCESS_KEY}
        bucket: backups.huginn.cnpg
        encrKey: "${VOLSYNC_ENCR_KEY}"
        name: backup-cnpg
        path: ""
        secretKey: ${VOLSYNC_SECRET_KEY}
        type: s3
        url: ${VOLSYNC_URL}
    securityContext:
      container:
        runAsUser: 0
        runAsGroup: 0
        readOnlyRootFilesystem: false
        runAsNonRoot: false
    workload:
      main:
        podSpec:
          type: Deployment
          replicas: 1
          containers:
            main:
              env: &huginn-env
                DOMAIN: huginn-test.${LOCAL_DOMAIN}
                DATABASE_ADAPTER: postgresql
                DATABASE_HOST: "{{ .Values.cnpg.main.creds.host }}"
                DATABASE_PORT: 5432
                DATABASE_NAME: "{{ .Values.cnpg.main.database }}"
                DATABASE_USERNAME: "{{ .Values.cnpg.main.user }}"
                DATABASE_PASSWORD: "{{ .Values.cnpg.main.creds.password }}"
                DO_NOT_CREATE_DATABASE: "true"

                # non-chart values?
                APP_SECRET_TOKEN: ${HUGINN_APP_SECRET_TOKEN}
                INVITATION_CODE: ${HUGINN_INVITATION_CODE}
              probes:
                readiness:
                  enabled: true
                  type: tcp
                  port: "{{ .Values.service.main.ports.main.port }}"
                liveness:
                  enabled: true
                  type: tcp
                  port: "{{ .Values.service.main.ports.main.port }}"
                startup:
                  enabled: true
                  type: tcp
                  port: "{{ .Values.service.main.ports.main.port }}"
      worker:
        enabled: true
        replicas: 1
        type: Deployment
        podSpec:
          containers:
            worker:
              primary: true
#              imageSelector: "{{ .Values.image }}"
              enabled: true
              command:
                - /scripts/init
                - bin/threaded.rb
#              env: {{ .Values.workload.main.podSpec.containers.main.env | deepCopy }}
              env: *huginn-env
              probes:
                readiness:
                  enabled: false
                liveness:
                  enabled: false
                startup:
                  enabled: false
    service:
      main:
        targetSelector: main
        ports:
          main:
            port: 3000
            protocol: http
            targetSelector: main
    cnpg:
      main:
        cluster:
          storage:
            storageClass: longhorn-cnpg
          walStorage:
            storageClass: longhorn-cnpg
        enabled: true
        pgVersion: 16
        user: huginn
        database: huginn_production
        # non-chart values
#        mode: recovery
        backups:
          enabled: true
          credentials: backup-cnpg
#        recovery:
#          credentials: backup-cnpg

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: huginn-test.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
          homepage:
            enabled: true
            name: Huginn
            description: Create agents that monitor and act on your behalf. Your agents are standing by!
            group: Automation
            widget:
              enabled: false
