# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: huginn
  namespace: huginn
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 15.1.10
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: huginn
  values:
    TZ: Asia/Yekaterinburg
    image:
      repository: ghcr.io/huginn/huginn-single-process
      pullPolicy: IfNotPresent
      tag: e95438fe02e9fc5be85101029b2e4441d0822328
    credentials:
      backup-cnpg:
        accessKey: ${VOLSYNC_ACCESS_KEY}
        bucket: backups.huginn.cnpg
        encrKey: "${VOLSYNC_ENCR_KEY}"
        name: backup-cnpg
        path: ""
        secretKey: ${VOLSYNC_SECRET_KEY}
        type: s3
        url: ${VOLSYNC_URL}
    workload:
      main:
        podSpec:
          type: Deployment
          replicas: 1
          containers:
            main:
              env: &huginn-env
                DOMAIN: huginn-test.${LOCAL_DOMAIN}
                DATABASE_ADAPTER: postgresql
                DATABASE_HOST: "{{ .Values.cnpg.main.creds.host }}"
                DATABASE_PORT: 5432
                DATABASE_NAME: "{{ .Values.cnpg.main.database }}"
                DATABASE_USERNAME: "{{ .Values.cnpg.main.user }}"
                DATABASE_PASSWORD: "{{ .Values.cnpg.main.creds.password }}"

                # non-chart values?
                APP_SECRET_TOKEN: ${HUGINN_APP_SECRET_TOKEN}
                INVITATION_CODE: ${HUGINN_INVITATION_CODE}
              probes:
                readiness:
                  enabled: true
                  type: tcp
                  port: "{{ .Values.service.main.ports.main.port }}"
                liveness:
                  enabled: true
                  type: tcp
                  port: "{{ .Values.service.main.ports.main.port }}"
                startup:
                  enabled: true
                  type: tcp
                  port: "{{ .Values.service.main.ports.main.port }}"
      worker:
        enabled: true
        primary: true
        imageSelector: "{{ .Values.image }}"
        replicas: 1
        type: Deployment
        podSpec:
          containers:
            worker:
              enabled: true
              command: /scripts/init bin/threaded.rb
#              env: {{ .Values.workload.main.podSpec.containers.main.env | deepCopy }}
              env: *huginn-env
    service:
      main:
        targetSelector: main
        ports:
          main:
            port: 3000
            protocol: http
            targetSelector: main
    cnpg:
      main:
        enabled: true
        pgVersion: 16
        user: huginn
        database: huginn_production
        # non-chart values
        mode: recovery
        backups:
          enabled: true
          credentials: backup-cnpg
        recovery:
          credentials: backup-cnpg

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: huginn-test.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
          homepage:
            enabled: true
            name: Huginn
            description: Create agents that monitor and act on your behalf. Your agents are standing by!
            group: Automation
            widget:
              enabled: false
