apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - volumeSnapshotClass.yaml
  - ingress.yaml
#  - cnpg-storage-class.yaml
  - jobs
