apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elib-to-ebook
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/elib-to-ebook/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

